name: Run NSEBSEBhavCopyDownload and Upload to Box on Windows

on:
  schedule:
    # Cron syntax: minute hour day(month) month day(week)
    # This example will run every day at 00:00 (midnight) UTC
    - cron: '30 14 * * 1-5'  # Runs every day at 2:30 PM UTC, which is 8:00 PM IST
  push:
    branches:
      - main

jobs:
  run-script-and-upload:
    runs-on: windows-latest  # Specify Windows environment

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout the code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    # Step 3: Install necessary Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the first Python script (NSEBSEBhavCopyDownload_V3.py)
    - name: Run NSEBSEBhavCopyDownload_V3.py
      run: |
        python NSEBSEBhavCopyDownload_V3.py

    # Step 5: Upload the generated CSV file to Box.com
    - name: Upload CSV to Box
      run: |
        python upload_to_box.py
      env:
        BOX_CLIENT_ID: ${{ secrets.BOX_CLIENT_ID }}
        BOX_CLIENT_SECRET: ${{ secrets.BOX_CLIENT_SECRET }}
        BOX_ENTERPRISE_ID: ${{ secrets.BOX_ENTERPRISE_ID }}
        BOX_JWT_PRIVATE_KEY: ${{ secrets.BOX_JWT_PRIVATE_KEY }}
        BOX_PUBLIC_KEY_ID: ${{ secrets.BOX_PUBLIC_KEY_ID }}
        BOX_PASSPHRASE: ${{ secrets.BOX_PASSPHRASE }}
