name: Run NSEBSEBhavCopyDownload and Upload to Box on Windows

on:
  schedule:
    # Cron syntax: minute hour day(month) month day(week)
    # This example will run every day at 00:00 (midnight) UTC
    - cron: '30 14 * * 1-5'  # Runs every day at 2:30 PM UTC, which is 8:00 PM IST
  push:
    branches:
      - main

jobs:
  run-script-and-upload:
    runs-on: windows-latest  # Specify Windows environment

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout the code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    # Step 3: Install necessary Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Step 4: Determine the  Latest ValueStocks CSV File from DropBox.
    - name: List files and get the most recent file
      id: list_files
      run: |
        # List files in the specified folder (/NSEBSEBhavCopy/ValueStocks)
        $response = curl -X POST https://api.dropboxapi.com/2/files/list_folder `
        --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" `
        --header "Content-Type: application/json" `
        --data '{"path": "/NSEBSEBhavCopy/ValueStocks"}'

        # Extract client_modified and path_display fields
        $files = $response | ConvertFrom-Json | ForEach-Object { $_.entries | ForEach-Object { [PSCustomObject]@{ Date = $_.client_modified; Path = $_.path_display } } }

        # Sort by date and get the most recent file
        $most_recent_file = $files | Sort-Object Date -Descending | Select-Object -First 1

        # Output the most recent file path to the environment
        Write-Output "Most recent file path: $($most_recent_file.Path)"
        echo "MOST_RECENT_FILE=$($most_recent_file.Path)" | Out-File -FilePath $env:GITHUB_ENV -Append

    # Step 5: Download the  Latest ValueStocks CSV File from DropBox.
    - name: Download most recent file from Dropbox and save with same name
      run: |
        $filename = "${{ env.MOST_RECENT_FILE }}" -replace '.*/', ''
        Write-Output "Downloading file: $filename"
        if (-not (Test-Path ".\")) {
          New-Item -Path ".\" -ItemType Directory
        }
        curl -X POST https://api.dropboxapi.com/2/files/download `
        --header "Authorization: Bearer ${{ secrets.DROPBOX_ACCESS_TOKEN }}" `
        --header "Dropbox-API-Arg: '{\"path\": \"${{ env.MOST_RECENT_FILE }}\"}'" `
        --output "./$filename"
        
    # Step 6: Run the first Python script (NSEBSEBhavCopyDownload_V3.py)
    #- name: Run NSEBSEBhavCopyDownload_V3.py
    #  run: |
    #    python NSEBSEBhavCopyDownload_V3.py

      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }} 
